name: deploy-myst-site-preview
on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - closed
permissions:
  pull-requests: write
jobs:
  build-and-deploy-preview:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy preview 🚀
        uses: curvenote/action-myst-publish@main
        env:
          CURVENOTE_TOKEN: ${{ secrets.CURVENOTE_TOKEN }}
        with:
          latex_packages: apacite lineno morefloats ragged2e soul
          preview: true
          preview_subdomain: franklin-notebooks_now_myst_full
